### ISSUE TITLE
Support several proxies

### ISSUE THREAD

**Issue by paulosuzart** [ojkelly/bunjil#20]
Bunjil works spinning up a koa server for itself, what makes it, at first, unsuited for using as a lib embedded in other projects. What is fine, but in this case it would be great if bunjil could support several proxies instead of one, and then route internally to the appropriate proxy instance by host name.

Say you setup bunjil at `app1.example.com`, you will then proxy requests to `upstream1.com`, but what if I want the same bunjil to answer requests to `app2.example.com` pointing to another upstream server and using different set of policies?

The idea is to support several proxy front ends that are independently configured with policies and back end schemas, but all in the same koa server where requests could be routed by hostname.

EDIT: It would be like having a `addProxy` to `bunjil` instance instead of `addSchema`. `addSchema` would be available via `bunjil.getProxy("app1.example.com").addSchema(...)`.

Is there any plan to make this happen?

**Comment by ojkelly** [comment]
So in addition to proxying GraphQL, this issue is about straight http proxying? I’m not sure node is best placed for a task like that.

**Comment by paulosuzart** [comment]
Hi Owen, not exactly. I think I'm failing to explain the cases.

Bunjil is already an http proxy, the point is that it proxies N schemas by merging everything into a single exposed s

**Comment by paulosuzart** [comment]
Here another example. Suppose you have two completely independt applications (A and B), each with its own schemas. They might be from different deppartments or even different companies but we decide to bunjil in front of them. 

The idea is to not join both schemas into one and serve in a single schema stiched by bunjil, instead I want to create two bunjil instances (`new Bunjil(...)`) one for each back end schema.

The outcome would be a single node js process with two Bunjil instances but a single koa server as you already have. The difference is that the request will be served by whatever Bunjil instance that is responsible for that hostname.

`appA.example.com ---> goes to bunjil Object instance A` and
`appB.example.com ---> goes to bunjil Object instance B`.

There is no mistery the point is that Bunjil classe has a koa server attached to it so it is not possible to cover the scenario explained above.

**Comment by paulosuzart** [comment]
Or basically I'm suggesting to change from this:

https://imgur.com/a/lWw5Y

to this:

https://imgur.com/a/dHOHW

**Comment by ojkelly** [comment]
Yep I get you now.

But I think this is at odds with the design, and the solution would be to run 2 Bunjil instances on two servers (ideally in containers).

There’s two reasons, the first ideological and the second practical.

The first reason, is that I want Bunjil to be safe and secure by default. Most of doing that I think is in the interface Bunjil exposes. A single GraphQL schema can inherently be composed of multiple upstream GraphQL servers.

So the intention here is that you would merge your backend upstreams into one public schema. It gives you one endpoint to focus on, one to secure, one to auth* and one to scale.

There are some tools that let you merge schema’s and namespace them (if you need separation from  the other schemas your merging for say naming conflicts).

The second, is that Bunjil’s written with the above in mind. It would need a decent rearranging to make the above work.

Which I think would only confuse things.

This is all bearing in mind the solution to this, have multiple differently configured Bunjil instances. You could also supply the same set of policies to both if you wanted to.
